server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

file:
  # 图片保存地址
  qrcode: D://

login:
  appId: #小程序appid
  secret: #小程序密钥
  authpage: pages/auth/auth #小程序认证界面,扫码后将跳转到这个界面